version: '3.8'

services:
  symfony:
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./back/:/var/www

  angular:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./front/:/var/www

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db

volumes:
  db-data: