version: '3.8'

services:
  symfony:
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./back/:/var/www

  angular:
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./front/:/var/www

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-data: